replicaCount: 2
image:
  repository: ecr-repo-endpoint
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 2000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

serviceAccount:
  create: true
  name: "python-backend-sa"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50
  memoryUtilization: 50

rds:
  endpoint: "rds.example.com"

networkPolicy:
  enabled: true
  ingress:
    - fromPodSelector:
        matchLabels:
          open.innovation.ai/application: nginx
