apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    open.innovation.ai/application: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      open.innovation.ai/application: nginx
  template:
    metadata:
      labels:
        open.innovation.ai/application: nginx
    spec:
      serviceAccountName: {{ if .Values.serviceAccount.enabled }}nginx-sa{{ end }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            fsGroup: {{ .Values.securityContext.fsGroup }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
      nodeSelector:
        open.innovation.ai/node-type: cpu
