apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    open.innovation.ai/application: nginx
spec:
  selector:
    open.innovation.ai/application: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
