name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS OIDC authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-actions-role
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run SonarQube Quality Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-backend-app \
            -Dsonar.sources=backend/ \
            -Dsonar.host.url=https://sonarqube.example.com \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

      - name: Build Docker Image
        run: |
          docker build -t my-backend-app:$GITHUB_SHA backend/
        
      - name: Authenticate to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
      
      - name: Tag Docker Image
        run: |
          docker tag my-backend-app:$GITHUB_SHA ${{ secrets.ECR_REGISTRY }}/my-backend-app:$GITHUB_SHA

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/my-backend-app:$GITHUB_SHA

      - name: Scan Docker Image for Vulnerabilities
        run: |
          aws ecr start-image-scan --repository-name my-backend-app --image-id imageTag=$GITHUB_SHA
        continue-on-error: true

      - name: Update Helm Chart with New Image SHA
        run: |
          cd backend/charts/my-backend-app
          sed -i "s/tag: .*/tag: $GITHUB_SHA/" values.yaml
          git add values.yaml
          git commit -m "Update image tag to $GITHUB_SHA"
          git push origin master
          
      - name: Send Deployment Notification Email
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3
        with:
          from: 'github@openinnovation.ai'
          to: 'devops@openinnovation.ai'
          subject: 'Backend App Docker Image Pushed & Helm Chart Updated'
          body: |
            The Docker image for the backend app has been successfully pushed to ECR and the Helm chart has been updated with the new image tag: $GITHUB_SHA.
        
  notify_on_failure:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send failure notification email
        uses: dawidd6/action-send-mail@v3
        with:
          from: 'github@openinnovation.ai'
          to: 'devops@openinnovation.ai'
          subject: 'Backend CI/CD Pipeline Failed'
          body: |
            The backend CI/CD pipeline failed at one of the steps. Please check the GitHub Actions logs for more details.
